import { Doc } from "@/app/_types";

// eslint-disable-next-line import/no-unused-modules
export const documents: Doc[] = [
  {
    id: 1,
    name: "Document 1",
    type: "pdf",
    tags: ["important", "work"],
    last_modified: "2024-02-18T12:30:00Z",
    isFav: true,
    assigned_users: [
      {
        id: 1,
        name: "John Doe",
        link: "https://example.com/johndoe",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 2,
        name: "Alice Smith",
        link: "https://example.com/alicesmith",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 13,
        name: "Ethan Baker",
        link: "https://example.com/ethanbaker",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 14,
        name: "Ava Murphy",
        link: "https://example.com/avamurphy",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 13,
        name: "Ethan Baker",
        link: "https://example.com/ethanbaker",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 14,
        name: "Ava Murphy",
        link: "https://example.com/avamurphy",
        imageUrl: "https://loremflickr.com/300/300/",
      },
    ],
  },
  {
    id: 2,
    name: "Document 2",
    type: "word",
    tags: ["personal"],
    last_modified: "2024-02-17T10:45:00Z",
    isFav: false,
    assigned_users: [
      {
        id: 3,
        name: "Bob Johnson",
        link: "https://example.com/bobjohnson",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 4,
        name: "Emily Davis",
        link: "https://example.com/emilydavis",
        imageUrl: "https://loremflickr.com/300/300/",
      },
    ],
  },
  {
    id: 3,
    name: "Document 3",
    type: "excel",
    tags: ["project", "notes"],
    last_modified: "2024-02-16T08:15:00Z",
    isFav: true,
    assigned_users: [
      {
        id: 5,
        name: "Michael Brown",
        link: "https://example.com/michaelbrown",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 6,
        name: "Emma Wilson",
        link: "https://example.com/emmawilson",
        imageUrl: "https://loremflickr.com/300/300/",
      },
    ],
  },
  {
    id: 4,
    name: "Document 4",
    type: "excel",
    tags: ["finance", "report"],
    last_modified: "2024-02-15T14:20:00Z",
    isFav: false,
    assigned_users: [
      {
        id: 7,
        name: "Sarah Taylor",
        link: "https://example.com/sarahtaylor",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 8,
        name: "David Martinez",
        link: "https://example.com/davidmartinez",
        imageUrl: "https://loremflickr.com/300/300/",
      },
    ],
  },
  {
    id: 5,
    name: "Document 5",
    type: "pptx",
    tags: ["presentation", "meeting"],
    last_modified: "2024-02-14T16:40:00Z",
    isFav: true,
    assigned_users: [
      {
        id: 9,
        name: "Sophia Garcia",
        link: "https://example.com/sophiagarcia",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 10,
        name: "James Rodriguez",
        link: "https://example.com/jamesrodriguez",
        imageUrl: "https://loremflickr.com/300/300/",
      },
    ],
  },
  {
    id: 6,
    name: "Document 6",
    type: "word",
    tags: ["research", "paper"],
    last_modified: "2024-02-13T18:50:00Z",
    isFav: false,
    assigned_users: [
      {
        id: 11,
        name: "Olivia Wilson",
        link: "https://example.com/oliviawilson",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 12,
        name: "Daniel Lee",
        link: "https://example.com/daniellee",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 13,
        name: "Ethan Baker",
        link: "https://example.com/ethanbaker",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 14,
        name: "Ava Murphy",
        link: "https://example.com/avamurphy",
        imageUrl: "https://loremflickr.com/300/300/",
      },
    ],
  },
  {
    id: 7,
    name: "Document 7",
    type: "pdf",
    tags: ["research", "study"],
    last_modified: "2024-02-12T20:10:00Z",
    isFav: true,
    assigned_users: [
      {
        id: 13,
        name: "Ethan Baker",
        link: "https://example.com/ethanbaker",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 14,
        name: "Ava Murphy",
        link: "https://example.com/avamurphy",
        imageUrl: "https://loremflickr.com/300/300/",
      },
    ],
  },
  {
    id: 8,
    name: "Document 8",
    type: "word",
    tags: ["project", "proposal"],
    last_modified: "2024-02-11T22:30:00Z",
    isFav: false,
    assigned_users: [
      {
        id: 15,
        name: "Liam Turner",
        link: "https://example.com/liamturner",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 16,
        name: "Mia Collins",
        link: "https://example.com/miacollins",
        imageUrl: "https://loremflickr.com/300/300/",
      },
    ],
  },
  {
    id: 9,
    name: "Document 9",
    type: "excel",
    tags: ["finance", "budget"],
    last_modified: "2024-02-10T11:45:00Z",
    isFav: true,
    assigned_users: [
      {
        id: 17,
        name: "Noah Adams",
        link: "https://example.com/noahadams",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 18,
        name: "Charlotte Rivera",
        link: "https://example.com/charlotterivera",
        imageUrl: "https://loremflickr.com/300/300/",
      },
    ],
  },
  {
    id: 10,
    name: "Document 10",
    type: "excel",
    tags: ["notes", "meeting"],
    last_modified: "2024-02-09T09:00:00Z",
    isFav: false,
    assigned_users: [
      {
        id: 19,
        name: "William Ward",
        link: "https://example.com/williamward",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 20,
        name: "Grace Ramirez",
        link: "https://example.com/graceramirez",
        imageUrl: "https://loremflickr.com/300/300/",
      },
    ],
  },
  {
    id: 11,
    name: "Document 11",
    type: "pdf",
    tags: ["report", "analysis"],
    last_modified: "2024-02-08T13:20:00Z",
    isFav: true,
    assigned_users: [
      {
        id: 21,
        name: "Alexander Gray",
        link: "https://example.com/alexandergray",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 22,
        name: "Chloe Stewart",
        link: "https://example.com/chloestewart",
        imageUrl: "https://loremflickr.com/300/300/",
      },
    ],
  },
  {
    id: 12,
    name: "Document 12",
    type: "word",
    tags: ["presentation", "training"],
    last_modified: "2024-02-07T15:40:00Z",
    isFav: false,
    assigned_users: [
      {
        id: 23,
        name: "Benjamin Cooper",
        link: "https://example.com/benjamincooper",
        imageUrl: "https://loremflickr.com/300/300/",
      },
      {
        id: 24,
        name: "Zoe Jenkins",
        link: "https://example.com/zoejenkins",
        imageUrl: "https://loremflickr.com/300/300/",
      },
    ],
  },
];
